export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ADMIN_LOGOUT = "GET_ADMIN_LOGOUT";
export const STATE_LOADING = "STATE_LOADING";
export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const BRAND_STATE_LOADING = "BRAND_STATE_LOADING";
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ALL_SUB_CATEGORY = "GET_ALL_SUB_CATEGORY";
export const CATEGORY_STATE_LOADING = "CATEGORY_STATE_LOADING";
export const ADD_BUTTON_LOADING = "ADD_BUTTON_LOADING";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_BRAND__BUTTON_LOADING = "ADD_BUTTON_LOADING";
export const ADD_BRAND = "ADD_BRAND";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
